set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSROOT "$(TOOLCHAIN_DIR)")
set(QT_HOST_PATH /usr/lib/qt6)

set(CMAKE_C_COMPILER "$(TARGET_CROSS)gcc")
set(CMAKE_CXX_COMPILER "$(TARGET_CROSS)g++")
set(CMAKE_AR "$(TARGET_CROSS)ar")
set(CMAKE_RANLIB "$(TARGET_CROSS)ranlib")
set(CMAKE_OBJCOPY "$(TARGET_CROSS)objcopy")

set(CMAKE_FIND_ROOT_PATH "$(STAGING_DIR)")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
